### PR TITLE
minor revisions to respectful communication

### LINKED ISSUE #154: Unedited Guidelines For Respectful Communication
https://haskell.foundation/guidelines-for-respectful-communication/ still refers to "Haskell committee" and its organisational structure instead of Haskell Foundation.

### PR DESCRIPTION
**Pull request by silky**
attempts to resolve #154

### CODE REVIEW

**Comment by goldfirere** [comment]
Thanks for suggesting concrete improvements! I'm not sure I fully agree here, though. The GRC as posted on the website is adoptable by any Haskell group. Maybe the word "committee" is too strong? That is, I see the GRC as applying to the board + employees of the HF. But any other group of Haskellers, be they a committee or maintainers of a project or just a loose band, should be able to adopt the GRC. So I think I would favor a change to refer to "Haskell team" or "Haskell group", and then change the references to chair to talk about "leader" or something.

Maybe I'm trying too hard to make this applicable beyond the HF, but I think it is more useful when the GRC can easily be adopted without adaptation.

(To be clear, I do think that its wording as is makes it sound like it doesn't apply to the HF, which is problematic.)

**Comment by silky** [comment]
Mm I see your point, and I agree I think.

Because I see this being utilised by #345 ; perhaps it makes sense to slightly change things to serve two purposes:

1. Like #345, it would be a set of _guidelines_, written generically as you suggested, that any group can follow,
2. It's then made clear that the HF itself follows this procedure, with the repsective roles field in?

Is that what you're suggesting anyway? In which case I'm happy to re-word as you suggest, and then revisit once some progress on #345 is made?

**Comment by goldfirere** [comment]
Yes, I think you capture my intent there. The top of the document says that the HF adopts the GRC, but maybe the GRC should somehow be a separate document that the HF then accepts. Not sure -- other than the fact that the current state is manifestly confusing ("manifestly": people are getting confused by it!). Thank you!

**Comment by silky** [comment]
Closing so this doesn't go stale.

**Pull request closed without merging**
