### PR TITLE
Add Platonic.Systems as in kind donator

### PR DESCRIPTION
**Pull request by leomayleomay**

### CODE REVIEW

**Review by tomjaguarpaw — APPROVED** [review]

**Comment by tomjaguarpaw** [comment]
Looks good to me! We should wait for @nikivazou who is travelling this week, but will be available next week.

**Comment by leomayleomay** [comment]
> Looks good to me! We should wait for @nikivazou who is travelling this week, but will be available next week.

@tomjaguarpaw  sure thing, thank you for letting me know

**Review by nikivazou — APPROVED** [review]

**Comment by leomayleomay** [comment]
@nikivazou thank you for approving the PR, would you please help to rerun the workflow?

**Comment by nikivazou** [comment]
I rerun it, but I think it will still fail (something is off with the CI build, that I will take a look soon).

**Comment by leomayleomay** [comment]
@nikivazou you're right, it fails again ...

**Pull request merged**
