### PR TITLE
Add nix support via stacklock2nix

### PR DESCRIPTION
**Pull request by silky**
Allows building the Haskell part of the project with a nix flake via stacklock2nix.

Adds all the stacklock2nix files, and modifies the stack.yaml to point to the stack-shell.nix.

### CODE REVIEW

**Comment by goldfirere** [comment]
I'm sadly at a loss to be able to review this. But more important to me than the implementation is the design: Why do we want this ability? How hard will this be to maintain? What does adding this feature prevent us from doing in the future? Are people who don't use this new functionality affected?

**Comment by silky** [comment]
> Why do we want this ability? 

Depending on how you live, if you use NixOS using _something_ like this is the only way to continue to build the project with an isolated `stack` installation, while also allowing non-NixOS people to continue using stack as normal.

> How hard will this be to maintain?

Shouldn't be too hard. If someone doesn't use Nix, they don't need to do anything; they can just add/remove dependencies and not touch the Nix files. It could happen that a new dependency isn't in nixpkgs (unlikely) or doesn't build well ( maybe 10% chance 😀 ) then someone would need to modify `nix/overlay.nix` to fix that in whatever way was necessary.

In theory, one could set up CI to always build the Nix process to verify that hasn't happened, and prompt a fix if it does; but I'd consider that not particularly important right now, because it will only impact people that will actually be motivated to just fix it if it breaks anyway; i.e. someone who's using this shell. I also wouldn't be expecting non-nix people to have to maintain it anyway; the whole idea is that it'd be mostly opaque to people who avoid using it.

> What does adding this feature prevent us from doing in the future? 

Nothing really.

If we choose to upgrade our stack LTS, say, then this is something that needs to go hand-in-hand with a few changes in the Nix files; and again we could use GitHub actions to check that; but I'd only set that up a bit later, and there'd be a few other things to do if we'd do full CI using Nix (i.e. a bit of caching, etc).

> Are people who don't use this new functionality affected?

Not really.

As mentioned above, in theory there's a bit of busywork to check that changes to the stack files alone still result in successful Nix builds; but "probably" it will be fine, and if not, I think it's reasonable to expect the first person who runs the nix shell to at least report the error, so that someone can fix it.

It could be incorporated into the CI, but it's a bit involved because you need to do a bit of work to set up caching correctly so Nix doesn't waste too much time re-building constantly. I don't feel compelled to do that at this precise moment, but it would be good to do one day. In the case that it _was_ set up though, I don't think it'd be polite to require non-Nix users to fix the Nix build; so the CI would only be a hint of what commit broke it, rather than preventing a merge. In which case, for me, I think it's even less valuable, because that'd just be found out anyway, and probably typically "easy" enough to fix, in the typical Nix fashion :)

--- 

Some alternatives to this _particular_ approach would be:

1. Drop `stack` for the project entirely and just use `cabal`; this means we could avoid stacklock2nix, but it has a few issues of it's own.
2. Just describe to people on NixOS how to build this project with changes to your global stack config; I'm personally against this for a few reasons, but one reason is that it doesn't play well with stacklock2nix for other reasons.

I hope this helps.

**Comment by goldfirere** [comment]
Thanks for these helpful responses @silky. My chief worry here -- as you can probably surmise -- is the impact this addition has on website contributors. Already we've identified that the website is harder to update than we'd like (specifically, we'd like to remove the tailwind dependency), and I'm a little worried that this new addition makes this situation worse (for the majority of would-be contributors). Your answers allay the concerns somewhat -- this doesn't sound like it would be too burdensome -- but I'd want to hear from other contributors that indeed this would be helpful to them.

**Comment by silky** [comment]
Yes, very reasonable.

Here's my simple thoughts:

1. This helps people on NixOS build the project - So, question: is there anyone out there on NixOS and building this project in another way? Happy to follow that advice.
2. I'd be happy to update the readme/contributing to say something like "if you don't use the nix flake, don't worry about it, it'll be maintained by it's users", and then maybe list at least two people who are willing to maintain it.

Is there anyone else out there that would be so willing, or otherwise has an opinion?

**Comment by nomeata** [comment]
I use nix and don't use stack usually, and have built this by using nix to get a GHC with hakyll installed, and then used `cabal` to build and run the site generator. It worked, but wasn't a particularly recommendabale setup, so I'd welcome a better maintained nix shell setup (I think I only needed a nix shell, not a nix build of the page, if that changes things.)

**Comment by silky** [comment]
Closing this so it doesn't go stale.

**Pull request closed without merging**
