### PR TITLE
Organize projects page by project status.

### PR DESCRIPTION
**Pull request by myShoggoth**

### CODE REVIEW

**Comment by goldfirere** [comment]
Perhaps I should know how to do this, but how can I preview the new page?

**Comment by myShoggoth** [comment]
> Perhaps I should know how to do this, but how can I preview the new page?

I wish it were simple, and getting screenshots is not, either (at least on Windows). If you have Nix locally you can ./build.sh and ./watch.sh

**Comment by tomjaguarpaw** [comment]
We could set up a Github action to install Nix and then run `./build.sh` and `./watch.sh`, putting the result in an artifact. That's what Tikhon Jelvis and I did for the Haskell.org repo

https://github.com/haskell-infra/www.haskell.org/blob/ed21e6f047ee64dc33bdc615096d810ec251f4bb/.github/workflows/main.yml#L14

It's probably a good few hours work to get running, unless one is very familiar with both Nix and Github actions, so I'm not sure where this comes in the relative priority of tasks for the site of HF in general.

**Comment by myShoggoth** [comment]
We have #23 to try to encapsulate what we want here.  What I'd ideally like:

1. When a CI build happens it generates the site via Hakyll, which is automatically checked in so you don't have to do that yourself. Ideally it would be in a different branch or something. I did https://github.com/myShoggoth/myShoggoth.github.io/blob/hakyll/.circleci/config.yml for my own website using Hakyll.
2. It would be extra cool to have the build results for PRs put on some url so people could try it out, like "branches.haskell.foundation/<branchname>", but that gets much more complex.
3. I believe the nix infrastructure here exists to enable a bunch of CSS/JS infrastructure. I'm not sure we really need all that complexity, if we could remove the Nix dependency it would be much easier to work on the site and see it locally.

**Comment by Kleidukos** [comment]
Here is a screenshot of the new page 
image

**Review by Kleidukos — APPROVED** [review]
After having reviewed the changes, LGTM.

**Pull request merged**
