### PR TITLE
bodigrim podcast

### PR DESCRIPTION
**Pull request by nikivazou**

### CODE REVIEW

**Comment by nikivazou** [comment]
> Usually, you merge these directly - is this waiting on something that I need to help with?

I was actually wondering if @Bodigrim had any other links than github that we should add. But merged and we can add them later, if any

**Comment by david-christiansen** [comment]
The goal was not to rush you - just wanted to make sure it wasn't me who was in the way :-)

**Comment by nikivazou** [comment]
> The goal was not to rush you - just wanted to make sure it wasn't me who was in the way :-)

I know :)

**Comment by Bodigrim** [comment]
What? The deal was that I’ll get the edited version to check before it’s published. And now I learn about it a week after publication, and just accidentally, because of being tagged. This is not appropriate. 

> Bodigrim went from a mathematician in theory to a failed PhD developer to the chair of core libraries committee. In this episode we discuss if he prefers number theory or Haskell, is he prefers working with compilers or PhD frameworks

TIL that I failed my PhD. I know that my English asks for improvement, but I'd expect at least a single human to find time in the course of three months after recording to validate whether the output of speech recognition AI fed into abstract generating AI makes any sense. "PhD developer"! "PhD frameworks"!

Celebrate, not celibate. PHP, not PhD.

Jokes aside, I expect a separate errata issued on all platforms. Spreading misinformation about my degree is harmful.

**Comment by david-christiansen** [comment]
Hi @Bodigrim 

I'm very sorry for this. Would you like me to take it down until it can be fixed, or simply get it fixed ASAP? Do you want to check the audio? I'm not sure what the correct text should be here, but what about:

> In this episode Joachim Breitner and Wouter Swierstra talk to Andrew Lelechenko, also known as Bodigrim. Bodigrim went from a being a mathematician to the chair of the core libraries committee. In this episode, we discuss whether he prefers number theory or Haskell, whether he prefers working with compilers or pure mathematics, and whether he prefers high salaries for Haskell developers or breaking changes to the `base` library. 

I'll certainly post corrections publicly on Discourse and through all our social media outlets.

**Comment by david-christiansen** [comment]
(given that you're on vacation and that this is a bit of a rush matter, I'll update it to this text at 10:00 CET (in 3.5 hours), as it seems to be a clear improvement, and then we can iterate/take down as you wish from there)

**Comment by nomeata** [comment]
I’m indeed sorry, there was a gap in the process where Niki didn't know that the deal was that you get the edited version ahead of time (which we do on request, but not always). We’ll improve on that.

Also sorry for the typo in the description. We tend to have typos, it’s the “Haskel Interlude” on twitter after all, but at least that one is quick to fix (just `s/Phd/PHP` on buzzsprout; @david-christiansen thanks for fixing the text on the website)

**Comment by david-christiansen** [comment]
I did some other stylistic tweaks on the website text - should I port those to Buzzsprout or port the Buzzsprout text here?

**Comment by nomeata** [comment]
I’ll take yours to buzzsprout

**Comment by nomeata** [comment]
Great!

**Pull request merged**
