### PR TITLE
Fix mobile nav to match nav, particularly with podcast link.

### PR DESCRIPTION
**Pull request by myShoggoth**

### CODE REVIEW

**Comment by elland** [comment]
This feels like a lot of code repetition that could more easily be served by a [partial](https://jaspervdj.be/hakyll/reference/Hakyll-Web-Template.html).

**Comment by myShoggoth** [comment]
Agreed, we are not taking advantage of Hakyll as much as we should at this point, basically due to lack of bandwidth.

**Comment by elland** [comment]
@myShoggoth understood. If that’s ok, I can open a pr later this week adding rss support and cleaning up some of these.

**Comment by myShoggoth** [comment]
We welcome PRs with open arms!

**Pull request merged**
