### PR TITLE
Fix In-Kind Donations in mobile device

### PR DESCRIPTION
**Pull request by leomayleomay**
* Before:

image

* After:
image

### CODE REVIEW

**Comment by leomayleomay** [comment]
@nikivazou would you please help to review this? cheers

**Comment by tomjaguarpaw** [comment]
This looks fine to me, assuming there is no regression for non-mobile devices!

**Comment by leomayleomay** [comment]
@tomjaguarpaw I recorded a gif to show how it looks in my laptop browser

Untitled

**Review by tomjaguarpaw — APPROVED** [review]

**Comment by leomayleomay** [comment]
@tomjaguarpaw the CI fails for some unknown reason, @nikivazou helped to fix it yesterday, while I am not quite sure what she did to get it green

**Comment by tomjaguarpaw** [comment]
This one still needs Niki to merge.

(I'm not sure she actually *did* get it green. My assumption was it deployed correctly despite CI failing, though my assumption may be wrong.)

**Comment by leomayleomay** [comment]
@tomjaguarpaw ahh, that actually makes sense, would you please loop her in? cheers

**Comment by myShoggoth** [comment]
Some historical context: The CI works correctly for deploying the site when merging into the `hakyll` branch, but not for other use cases.  You can check to see if the compile/site build steps work. Making the CI work correctly in other use cases is a useful contribution someone can make, and there's another PR trying to help that but I don't know if it fixes all the cases.

**Pull request merged**
