### PR TITLE
Resize sponsor logos

### PR DESCRIPTION
**Pull request by leomayleomay**
desktop

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks, this looks good to me!  @nikivazou ?

**Comment by nikivazou** [comment]
No resize, correct? 
I prefer that :)

**Comment by leomayleomay** [comment]
@nikivazou I did make the bronze sponsors smaller, otherwise, they look even bigger than gold and silver sponsors :)

Screen Shot 2022-04-12 at 8 21 14 PM

**Comment by leomayleomay** [comment]
the wording here is using `Monad`, `Applicative`, and `Functor`, not sure if we really want to replace them with `Gold`, `Silver`, and `Bronze`?

Screen Shot 2022-04-12 at 8 27 13 PM

**Comment by goldfirere** [comment]
@nikivazou brought this to my attention. I think we should keep the existing names for the categories, given that the current names are what sponsors are expecting. Maybe we should change them in the future, but I do think this is a larger conversation, and one which I expect @david-christiansen to take ownership of in due course.

As for resizing: I think the current resize (as merged) makes Functor too small. I can barely read some of the sponsors' names on my screen. Yet without resizing, some of the Functors look bigger than the others, which is no good either.

My general thought is that we should avoid making any policy decisions during this between-the-EDs time, unless we're somehow forced to do so. So my preference would have been not to have merged -- just based on this idea of holding the status quo. Furthermore, this change is more likely to annoy some sponsors than to make anyone happy. It's probably not worth the bother of undoing this either.

**Pull request merged**
