### PR TITLE
Properly unify nav and mobile nav structure, fix markup issues

### PR DESCRIPTION
**Pull request by jhrcek**
Hello @myShoggoth 
this is a followup to your change https://github.com/haskellfoundation/haskellfoundation.github.io/pull/87 which, with all due respect, was not implemented correctly.
You seem to have modified the html in `docs` directory directly.
But the proper way was to fix the templates under `site` and then **generate the contents of the docs folder** by running `./build.sh` in the root of the repo.

I did just that, respecting your changes and including few general markup fixes as follows
- the divs in the mobile nav had href attribute - this is not valid html and correspondingly had no effect (in the sense that those divs didn't work as a link)
- the mobile nav links were missing some css classes, so they were not properly nested - I added those.
- there were couple of elements with empty id attribute - I removed those
- the haskell foundation logos in the footer had a dead link - this has now been fixed by running `./build.sh`

Note: to understand what I changed just look at the files under `site/templates`. The rest of the changes (everything under `docs`) are just result of regenerating the site by running hakyll .

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
@jhrcek Are you saying that the `docs/` directory is generated from `site/` by running `./build.sh`? If so, does anyone know why `docs/` is checked in at all? (Perhaps that's how Github pages works?)

**Comment by elland** [comment]
@tomjaguarpaw 

>  (Perhaps that's how Github pages works?)

That's my understanding as well.

@jhrcek thanks for catching that.

**Comment by jhrcek** [comment]
Yes. I know that github pages allows you to publish html from selected subfolder on master branch of your repository.

Is that how this particular repository is setup? I can't say, because I don't have access to its settings, but I'm pretty sure

**Review by elland — APPROVED** [review]

**Comment by tomjaguarpaw** [comment]
Ah yes, it is explained at https://github.com/tomjaguarpaw/haskellfoundation.github.io/blob/master/CONTRIBUTING.md#building-the-site

**Comment by myShoggoth** [comment]
Thank you for fixing my mess!

**Pull request merged**
